sudo: required

services:
  - docker

before_install:
   - docker build -t krishnachalla/docker-react -f Dockerfile.dev .

script:
   - docker run -e CI=true krishnachalla/docker-react npm run test -- --coverage