sudo: required
services:
   - docker

before_install:
   - dokcer build -t krishnachalla/docker-react -f Dockerfile.dev .

script:
   - dcoker run krishnachalla/docker-react npm run test -- --coverage